name: Mobile App CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4   # updated to v4

      - name: Setup Node.js
        uses: actions/setup-node@v4 # updated to v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd MobileAppDemo
          npm install

      - name: Build Android APK
        run: |
          cd MobileAppDemo
          npx react-native build-android

      - name: Upload Artifact
        uses: actions/upload-artifact@v4  # updated to v4
        with:
          name: android-apk
          path: MobileAppDemo/android/app/build/outputs/apk/release/app-release.apk
